openqa.webserver/src/main/java/org/aksw/openqa/server/servlet/SearchServlet.java
package org.aksw.openqa.server.servlet;

import java.io.IOException;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.ServletException;
import javax.servlet.ServletOutputStream;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.aksw.openqa.component.param.IResultMap;
import org.aksw.openqa.component.param.IResultMapList;
import org.aksw.openqa.manager.plugin.PluginManager;
import org.aksw.openqa.manager.plugin.PluginManagerPool;
import org.aksw.openqa.server.ServerEnviromentVariables;
import org.aksw.openqa.server.util.ServerSearchUtil;
import org.apache.log4j.Logger;

/**
 * 
 * @author {@linkplain http://emarx.org}
 *
 */
@WebServlet(name = "api/rest/search", urlPatterns = { "/api/rest/search" })
public class SearchServlet extends HttpServlet {

	public final static String OUTPUT_CONTENT_PARAM = "content";
	public final static String OUTPUT_CONTENT_PARAM_TYPE_SPARQL = "sparql";
	public final static String INPUT_QUERY_PARAM = "q";

	/**
	 * 
	 */
	private static final long serialVersionUID = -5755833016211618969L;
	private static Logger logger = Logger.getLogger(SearchServlet.class);

	@Override
	public void init() throws ServletException {
	}

	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {

		logger.info("Starting a new openQA Call");
		Map<String, Object> servletParams = new HashMap<String, Object>();
		Enumeration<String> parameters = req.getParameterNames();
		while (parameters.hasMoreElements()) {
			String parameterName = parameters.nextElement();
			String parameter = req.getParameter(parameterName);
			servletParams.put(parameterName, parameter);
			logger.info("Processing param: " 
					+ parameterName + " = "
					+ parameter);
		}

		// setting up the context
		ServletOutputStream out = resp.getOutputStream();
		PluginManagerPool pool = (PluginManagerPool) ServerEnviromentVariables.getInstance().getParam(ServerEnviromentVariables.PLUGIN_MANAGER_POOL);
		PluginManager pluginManager = null;
		try {
			pluginManager = pool.borrowObject();
			IResultMapList<? extends IResultMap> result = ServerSearchUtil.search(servletParams, req, pluginManager);
			out.print(result.toJSON());
		} catch (Exception e) {
			logger.error("Exception executing search.", e);
		} finally {
			if(pluginManager != null) {
				pool.returnObject(pluginManager);
			}
		}
	}
}

openqa.webserver/src/main/java/org/aksw/openqa/server/view/controller/SearchViewController.java
package org.aksw.openqa.server.view.controller;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

import org.aksw.openqa.Properties;
import org.aksw.openqa.component.param.IResultMap;
import org.aksw.openqa.component.param.IResultMapList;
import org.aksw.openqa.component.providers.impl.RetrieverProvider;
import org.aksw.openqa.component.retriever.IResultEntryInstanciator;
import org.aksw.openqa.component.retriever.IResultEntryTriplestoreRetriever;
import org.aksw.openqa.component.retriever.PropertyEntry;
import org.aksw.openqa.component.retriever.ResultEntry;
import org.aksw.openqa.manager.plugin.PluginManager;
import org.aksw.openqa.manager.plugin.PluginManagerPool;
import org.aksw.openqa.server.ServerEnviromentVariables;
import org.aksw.openqa.server.util.ServerSearchUtil;
import org.apache.log4j.Logger;
import org.json.JSONException;

/**
 * 
 * @author {@linkplain http://emarx.org}
 *
 */
@ManagedBean(name="searchViewController")
@RequestScoped
public class SearchViewController implements Serializable {
	
	private static Logger logger = Logger.getLogger(SearchViewController.class);

	/**
	 * 
	 */
	private static final long serialVersionUID = -7988952280420748804L;
	
	@ManagedProperty("#{param.q}")
	private String query;
	
	@ManagedProperty("#{param.content}")
	private String content;
	
	private Integer resultSize = 0;

	public SearchViewController() {
	}
	
	public String getQuery() {
		return query;
	}
	
	public void setQuery(String query) {
		this.query = query;
	}
	
	public String getContent() {
		return content;
	}
	
	public void setContent(String content) {
		this.content = content;
	}
	
	public int getResultSize() {
		return this.resultSize;
	}
	
	public List<ResourceEntry> getResult() {
		Map<String, Object> params = new HashMap<String, Object>();
		List<ResourceEntry> resources = new ArrayList<ResourceEntry>();
		
		// check if the query is pre-defined		
		if(query != null) {
			params.put("q", query);
		}
		if(content != null) {
			params.put("content", content);
		}
		
		HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().
				getExternalContext().getRequest();
		PluginManagerPool pool = (PluginManagerPool) ServerEnviromentVariables.getInstance().getParam(ServerEnviromentVariables.PLUGIN_MANAGER_POOL);
		PluginManager pluginManager = null;
		try {
			pluginManager = pool.borrowObject();
			IResultMapList<? extends IResultMap> result = ServerSearchUtil.search(params, request, pluginManager);
			resultSize = result.size();
			for(IResultMap resultEntry : result) {
				if(resultEntry.contains(Properties.URI)) {
					String resource = resultEntry.getParam(Properties.URI, String.class);
					ResourceEntry e = new URIEntry(resource, pluginManager, Integer.toString(result.indexOf(resultEntry)));
					resources.add(e);
				} else if(resultEntry.contains(Properties.SPARQL)) {
					String sparql = resultEntry.getParam(Properties.SPARQL, String.class);
					ResourceEntry e = new SPARQLEntry(sparql, Integer.toString(result.indexOf(resultEntry)));
					resources.add(e);
				}
			}
		} catch (Exception e1) {
			logger.error("Error searching.", e1);
		} finally {
			if(pluginManager != null) {
				pool.returnObject(pluginManager);
			}
		}
		return resources;
	}
	
	public class ResourceEntry implements Serializable {
		/**
		 * 
		 */
		private static final long serialVersionUID = -787982225724615754L;
		String id;
		
		public ResourceEntry(String id) {
			this.id = id;
		}
		
		public String getId() {
			return id;
		}
		
		public boolean isSparql() {
			return false;
		}
		
		public boolean isGeospatial() {
			return false;
		}
	}
	
	public class URIEntry extends ResourceEntry {
		/**
		 * 
		 */
		private static final long serialVersionUID = -6402248767090179799L;
		String url;
		String json;
		String entryPath;
		Boolean isGeospatial = false;
		String lat;
		String lon;
		String label;
		String comment;
		String homepage;
		String imageURL;
		
		public URIEntry(String resource, PluginManager pluginManager, String id) {
			super(id);
			this.json = resource.replace("resource", "data") + ".json";
			this.url = resource;
			this.entryPath = resource.replace("http://dbpedia.org/resource/", "");
			try {
				load(url, pluginManager);
			} catch (Exception e) {
				logger.error("Error loadgin entity properties:" + url, e);
			}
		}

		@Override
		public boolean isGeospatial() {
			return isGeospatial;
		}
		
		private void load(String url, PluginManager pluginManager) throws IOException, JSONException {
			IResultEntryTriplestoreRetriever tripleStoreRetriever = pluginManager.getPlugin(RetrieverProvider.class, IResultEntryTriplestoreRetriever.class);
			String sparqlQuery =  "select ?p ?o where {?s ?p ?o. FILTER(?s = <" + url + ">). FILTER(!isLiteral(?o) || (langMatches(lang(?o), \"EN\"))) }";
			tripleStoreRetriever.retrieve(sparqlQuery, new IResultEntryInstanciator<Object>() {

				@Override
				public Object newInstance(ResultEntry entry) {
					String property = entry.getPropertyValue("p").toString();
					PropertyEntry o = entry.getProperty("o");

					if(property.equals("http://dbpedia.org/property/fullname")) {
						label = o.getValue().toString();
					} else if(property.equals("http://dbpedia.org/property/name")) {
						label = o.getValue().toString();
					} else if(property.equals("http://www.w3.org/2000/01/rdf-schema#label")) {
						label = o.getValue().toString();
					} else if(property.equals("http://www.w3.org/2003/01/geo/wgs84_pos#lat")) {
						isGeospatial = true;
						lat = o.getValue().toString();
					} else if(property.equals("http://www.w3.org/2003/01/geo/wgs84_pos#long")) {
						lon = o.getValue().toString();
					} else if(property.equals("http://www.w3.org/2000/01/rdf-schema#comment")) {
						comment = o.getValue().toString();
					} else if(property.equals("http://xmlns.com/foaf/0.1/depiction")) {
						imageURL = o.getValue().toString();
					} else	if(property.equals("http://xmlns.com/foaf/0.1/homepage")) {
						homepage = o.getValue().toString();
					}
					
					return null; // there is no need to return the Entry
				}

				@Override
				public boolean stop() {
					return false;
				}				
			});
		}
		
		public String getLat() {
			return lat;
		}
		
		public String getLon() {
			return lon;
		}
		
		public String getUrl() {
			return url;
		}
		
		public String getJson() {
			return json;
		}
		
		public String getEntryPath() {
			return entryPath;
		}
		
		public String getLabel() {
			return label;
		}
		
		public String getComment() {
			return comment;
		}
		
		public String getImageURL() {
			return imageURL;
		}
		
		public String getHomepage() {
			return homepage;
		}
		
//		private class EntityAttributes extends HashMap<String, String> {
//
//			/**
//			 * 
//			 */
//			private static final long serialVersionUID = -6975374213597324896L;
//			
//			String url;
//			public EntityAttributes(String url) {
//				this.url = url;
//			}
//			
//			public String getURL() {
//				return url;
//			}
//			
//			public void setUrl(String url) {
//				this.url = url;
//			}			
//		}
	}
	
	public class SPARQLEntry extends ResourceEntry {
		
		private static final long serialVersionUID = -1545984271398672497L;
		/**
		 * 
		 */
		String sparql;
		
		public SPARQLEntry(String content, String id) {
			super(id);
			this.sparql = content;
		}
		
		public String getContent() {
			return sparql;
		}
		
		@Override
		public boolean isSparql() {		
			return true;
		}
	}
}

openqa.webserver/WebContent/api.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></meta>
<title>#{applicationViewController.name}</title>
<link rel="stylesheet" type="text/css" href="resources/css/menu.css" />
<link rel="stylesheet" type="text/css" href="resources/css/openqa.css" />
<style type="text/css">
.aboutInfoGraphBox {
	vertical-align: top;
}
</style>
</h:head>
<h:body
	style="height: 100%; width: 100%; margin: 0px; font-family: arial, sans-serif">
	<!--START FLOAT MENU-->
	<!-- Barra superior -->
	<div
		style="position: relative !important; top: 0px; left: 0px; z-index: 3;">
		<div id="menu" class="menu"
			style="height: 38px; font-size: 12px; font-weight: bold; vertical-align: middle; background-color: black;">
			<div style="padding-top: 10px; float: left;">
				<a style="margin-left: 15px; text-decoration: none;" href="./">
					<span>Search</span>
				</a> 
				<a style="margin-left: 15px; text-decoration: none;"
					href="samples.xhtml"> <span>Samples</span>
				</a>
				<a style="margin-left: 15px; color: white;text-decoration: none;"
					href="api.xhtml"> <span>API</span>
				</a>
				<a style="margin-left: 15px; text-decoration: none;" target="_blank"
					href="http://openqa.aksw.org"> <span>openQA</span>
				</a>
			</div>
			<span> <a class="button_p"
				style="float: right; height: 30px; width: 64px; margin-top: 3px; margin-right: 15px; text-align: center; vertical-align: middle;"
				href="admin/manager.xhtml"> <img style="margin-top: 3px;"
					height="26" width="26" src="resources/images/settings.png"
					alt="Manager" />
			</a>
			</span>
		</div>
	</div>	
	<div
		style="background-color: rgb(241, 241, 241); box-shadow: 0px 3px 2px rgba(0, 0, 0, 0.25); margin: 10px; padding: 0px 10px 10px 10px;">
		<h1>API</h1>
		<div>
			<div style="padding: 0px 10px 10px 10px;">
				<h:outputText>
					<h2>REST</h2>
					<div class="ui-messages ui-widget"
						style="max-width: 500px; text-align: left; font-size: 12px;"
						aria-live="polite" data-summary="data-summary"
						data-detail="data-detail">
						It is also possible to access #{applicationViewController.name} platform via REST API.
					</div>
					<div class="ui-messages ui-widget"
						style="text-align: left; font-size: 12px;"
						aria-live="polite" data-summary="data-summary"
						data-detail="data-detail">
						<div class="ui-messages-info ui-corner-all">
							<ul>
								<li><span class="ui-messages-info-summary"> 
								The resulting entities are accessible via the search method in REST API, e.g. <a href="./api/rest/search?q=Leipzig">./api/rest/search?q=Leipzig</a>
								</span></li>
							</ul>
						</div>
					</div>
					<div class="ui-messages ui-widget"
						style="text-align: left; font-size: 12px;"
						aria-live="polite" data-summary="data-summary"
						data-detail="data-detail">
						<div class="ui-messages-info ui-corner-all">
							<ul>
								<li><span class="ui-messages-info-summary"> 
									The resulting SPARQL queries are accessible via the search method in REST API by specifying the content as SPARQL, e.g. <a href="./api/rest/search?q=Leipzig&amp;content=sparql">./api/rest/search?q=Leipzig&amp;content=sparql</a>
								</span></li>
							</ul>
						</div>
					</div>					
				</h:outputText>
			</div>
		</div>
	</div>
	<!--  /ui:repeat-->
</h:body>
</html>

openqa.webserver/WebContent/login.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<meta http-equiv="Content-Type"
		content="text/javascript; charset=UTF-8"></meta>
	<title>#{applicationViewController.name} - Login</title>
	<link rel="stylesheet" type="text/css" href="resources/css/login.css" />
</h:head>
<h:body>
	<section class="container">	
		<div class="login">
			<h1>Login to openQA</h1>
			<h:form>
				<p:messages id="messages" showDetail="true" closable="true"/>
				<p>
					<p:inputText id="login" value="#{loginSessionController.login}" />
					<p:watermark for="login" value="Login" />
				</p>
				<p>
					<p:password id="pass" value="#{loginSessionController.password}" />
					<p:watermark for="pass" value="Password" />
				</p>
				<!-- p class="remember_me">
		          <label>
		            <input type="checkbox" name="remember_me" id="remember_me">
		            Remember me on this computer
		          </label>
		        </p-->
				<p class="submit">
					<p:commandButton action="#{loginSessionController.login}"
						value="Login" ajax="true" process="@form" update="@form"/>
				</p>
			</h:form>
		</div>
		<div class="login-help">
			<!--p>Forgot your password? <a href="index.html">Click here to reset it</a>.</p-->
		</div>
	</section>
</h:body>
</html>

openqa.webserver/WebContent/search.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<meta http-equiv="Content-Type" content="text/javascript; charset=UTF-8"></meta>
	<title>#{applicationViewController.name}</title>
	
	<link rel="stylesheet" type="text/css" href="resources/css/singleEntity/layout.css"/>
	<link rel="stylesheet" type="text/css" href="resources/css/singleEntity/singleEntity.bundle.css"/>
	<link rel="stylesheet" type="text/css" href="resources/css/singleEntity/layout_ext.css"/>
	<link rel="stylesheet" type="text/css" href="resources/css/menu.css" />
	<link rel="stylesheet" type="text/css" href="resources/css/openqa.css" />
	<script src="resources/js/jquery-1.10.2.min.js"> </script>
	<script src="resources/js/openqa-util.js"> </script>
	<script src="resources/js/openqa.searchbutton.js"> </script>
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"/>
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css"/>
</h:head>
<h:body	style="height: 100%; width: 100%; margin: 0px; font-family: arial, sans-serif">
	<!--START FLOAT MENU-->
	<!-- Barra superior -->
	<div style="top: 0px; left: 0px; z-index: 3;">
		<div id="menu" class="menu"
			style="height: 38px; font-size: 12px; font-weight: bold; vertical-align: middle; background-color: black;">
			<div style="padding-top: 10px; float: left;">
				<a style="margin-left: 15px; color: white; text-decoration: none;" href="./">
					<span>Search</span>
				</a> 
				<a style="margin-left: 15px; text-decoration: none;"
					href="samples.xhtml"> <span>Samples</span>
				</a>
				<a style="margin-left: 15px; text-decoration: none;"
					href="api.xhtml"> <span>API</span>
				</a>
				<a style="margin-left: 15px; text-decoration: none;" target="_blank"
					href="http://openqa.aksw.org"> <span>openQA</span>
				</a>
			</div>
			<span> 
				<a class="button_p"
					style="float: right; height: 30px; width: 64px; margin-top: 3px; margin-right: 15px; text-align: center; vertical-align: middle;"
					href="admin/manager.xhtml"> <img style="margin-top: 3px;"
						height="26" width="26" src="resources/images/settings.png"
						alt="Manager" />
				</a>
			</span>
		</div>
	</div>
	<div>
		<div>
			<div style="margin-top: 10px; margin-left: 10px;">
				<a href="./">
					<div align="left" style="background: url(#{applicationViewController.logo}) no-repeat; background-size: 75px 40px; height: 40px; width: 75px; position: absolute;" />
				</a>
				<p:inputText id="searchInput"
					onkeypress="event.keyCode==13?window.location.href='search.xhtml?q='+searchInput.value:false;"
					onkeyup="h.href='search.xhtml?q='+searchInput.value;r.href='search.xhtml?q='+searchInput.value+'&amp;content=sparql';searchKeyup(event, $(PrimeFaces.escapeClientId('h')));"
					value="#{searchViewController.query}"
					style="width: 550px;font-size: x-large;height: 45px;margin-left: 90px;" />
					<a style="margin-left:10px" id="h" class="button_go button_openqa" href="search.xhtml?q=#{searchViewController.query}" onclick="PF('bui').show()">Graph Search</a> 
					<a style="margin-left:10px" id="r" class="button_robot button_openqa" href="search.xhtml?q=#{searchViewController.query}&amp;content=sparql" onclick="PF('bui').show()">I´m a robot</a>
			</div>
		</div>
	</div>
	<p:outputPanel id="searchResult">
		<p:blockUI block="searchResult" widgetVar="bui">			
		 	<p:graphicImage value="resources/images/loading-2.gif" style="height: 50px;" />
		 	Querying millions of facts...
		</p:blockUI>
		<!-- ui:repeat-->	
		<ui:repeat var="resourceEntry" value="#{searchViewController.result}" varStatus="status">
			<p:outputPanel rendered="#{!resourceEntry.sparql &amp;&amp; searchViewController.resultSize > 1}">
				<div style="height: auto; background-color: rgb(241, 241, 241); box-shadow: 0px 3px 2px rgba(0, 0, 0, 0.25); margin: 10px;">
					<h3 style="margin: 5px;">#{resourceEntry.label}</h3>
					<div id="content" style="height: auto;">
						<div class="media" style="margin:10px;">
							  <div class="media-left">
							  	<p:outputPanel rendered="#{resourceEntry.imageURL != null}">
								    <a href="#{resourceEntry.imageURL}">
								      <p:graphicImage value="#{resourceEntry.imageURL}" alt="#{resourceEntry.label}" style="height: 50px;" />						  
								    </a>
							    </p:outputPanel>	
							  </div>
							  <div class="media-body">
							    <h:outputText value="#{resourceEntry.comment}"/>						   
							  </div>						  
						</div>
						<p:outputPanel rendered="#{resourceEntry.homepage != null}">
								<a id="page#{resourceEntry.id}" style="margin: 10px; font-size: small" href="#{resourceEntry.homepage}"
									target="_blank">Homepage</a>
								<a id="wikiLink" style="margin: 10px; font-size: small;" href="http://wikipedia.org/wiki/#{resourceEntry.entryPath}"
									target="_blank">Wikipedia</a>
								<a id="dbLink" style="margin: 10px; font-size: small;" href="#{resourceEntry.url}"
									target="_blank">DBpedia</a>
						</p:outputPanel>		
						<p:outputPanel rendered="#{resourceEntry.homepage == null}">
							<a id="wikiLink" style="margin: 10px; font-size: small;" href="http://wikipedia.org/wiki/#{resourceEntry.entryPath}"
								target="_blank">Wikipedia</a>
							<a id="dbLink" style="margin: 10px; font-size: small;" href="#{resourceEntry.url}"
								target="_blank">DBpedia</a>
						</p:outputPanel>			
					</div>
				</div>
			</p:outputPanel>		
			<p:outputPanel rendered="#{!resourceEntry.sparql &amp;&amp; searchViewController.resultSize == 1}">
				<div class="container" style="width:inherit;">
					<div id="plans-top-mbox" 
					class="content-main" 
					style="float: none; width: auto; font-size:larger; visibility: visible; 
							margin: 30px;display: block;text-align:left;background-color:white;box-shadow: 0px 2px 10px #888888;">
						<div class="content-header" style="box-shadow:0px 1px 1px #DFDFDF; background-color:#F8F8F8;">
							<div class="header-inner" style="background-color:#F8F8F8;">
							  <h2 style="font-weight:bold;font-size:large;">#{resourceEntry.label}</h2>
							</div>
						</div>
						<div class="stream-container">				  	
							<div class="stream profile-stream">
								<div style="margin:20px;">								
									 <div class="media">
										  <div class="media-left">
										    <a href="#{resourceEntry.imageURL}">
										      <p:graphicImage rendered="#{!resourceEntry.geospatial}" value="#{resourceEntry.imageURL}" alt="#{resourceEntry.label}" style="height: 200px;" />
										      <p:graphicImage rendered="#{resourceEntry.geospatial}" value="http://maps.googleapis.com/maps/api/staticmap?center=#{resourceEntry.lat},#{resourceEntry.lon}&amp;zoom=13&amp;size=600x300&amp;maptype=roadmap&amp;markers=color:blue%7C#{resourceEntry.label}:S%7C#{resourceEntry.lat},#{resourceEntry.lon}&amp;sensor=false" alt="#{resourceEntry.label}" style="height: 200px;" />
										    </a>
										  </div>
										  <div class="media-body">
										    <h:outputText value="#{resourceEntry.comment}"/>
										  </div>
									</div>
								</div>
							</div>
						</div>
						<div class="flex-module profile-banner-footer clearfix">
							<div class="default-footer">
								<div class="user-actions btn-group not-following" style="width: 100%;">
									<a target="_blank" href="http://wikipedia.org/wiki/#{resourceEntry.entryPath}">
										<button style="width:100%;border-bottom-left-radius: 6px;border-bottom-right-radius: 6px;" 
													class="user-actions-follow-button js-follow-btn follow-button btn" type="button">
											<span class="button-text follow-text">
												 <i class="follow"></i>Wikipedia										
											</span>
										</button>
									</a>
								</div>
							</div>
						</div>					
					</div>				
					<span class="hrule collapsible_section_rule"></span>
				</div>				
			</p:outputPanel>		
			<p:outputPanel rendered="#{resourceEntry.sparql}">
				<div style="height: auto; background-color: rgb(241, 241, 241); box-shadow: 0px 3px 2px rgba(0, 0, 0, 0.25); margin: 10px;">
					<div id="content" style="height: auto;padding:30px">
						<a id="page#{resourceEntry.id}" style="margin: 10px; font-size: small;" href="http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&amp;query=#{resourceEntry.content}"
							target="_blank">
							#{resourceEntry.content}
						</a>
					</div>
				</div>
			</p:outputPanel>
		</ui:repeat>
		<p:outputPanel rendered="#{searchViewController.resultSize == 0}">
				<div style="height: auto; background-color: rgb(241, 241, 241); box-shadow: 0px 3px 2px rgba(0, 0, 0, 0.25); margin: 10px;">
					<div id="content" style="height: auto;padding:30px">
						<h:panelGrid columns="2" cellpadding="10">
			                <h:outputText
			                    value="Your question is very hard. I am still very young. :-(" />
			            </h:panelGrid>
					</div>
				</div>
		</p:outputPanel>
	</p:outputPanel>
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</h:body>
</html>